(function ($) {
  $.fn.datepicker.language["ko"] = {
    days: ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"],
    daysShort: ["일", "월", "화", "수", "목", "금", "토"],
    daysMin: ["일", "월", "화", "수", "목", "금", "토"],
    months: [
      "01월",
      "02월",
      "03월",
      "04월",
      "05월",
      "06월",
      "07월",
      "08월",
      "09월",
      "10월",
      "11월",
      "12월",
    ],
    monthsShort: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    today: "Today",
    clear: "Clear",
    dateFormat: "yyyy-mm-dd",
    timeFormat: "hh:ii:ss",
    firstDay: 0,
  };
  $.fn.datepicker.language["us"] = {
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    daysMin: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    months: [
      "01월",
      "02월",
      "03월",
      "04월",
      "05월",
      "06월",
      "07월",
      "08월",
      "09월",
      "10월",
      "11월",
      "12월",
    ],
    monthsShort: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    today: "Today",
    clear: "Clear",
    dateFormat: "yyyy-mm-dd",
    timeFormat: "hh:ii:ss",
    firstDay: 0,
  };
  $.fn.datepicker.language["vn"] = {
    days: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
    daysShort: ["C", "H", "B", "T", "N", "S", "B"],
    daysMin: ["C", "H", "B", "T", "N", "S", "B"],
    months: [
      "01월",
      "02월",
      "03월",
      "04월",
      "05월",
      "06월",
      "07월",
      "08월",
      "09월",
      "10월",
      "11월",
      "12월",
    ],
    monthsShort: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    today: "Today",
    clear: "Clear",
    dateFormat: "yyyy-mm-dd",
    timeFormat: "hh:ii:ss",
    firstDay: 0,
  };
  $.fn.datepicker.language["jp"] = {
    days: ["日", "月", "火", "水", "木", "金", "土"],
    daysShort: ["日", "月", "火", "水", "木", "金", "土"],
    daysMin: ["日", "月", "火", "水", "木", "金", "土"],
    months: [
      "01월",
      "02월",
      "03월",
      "04월",
      "05월",
      "06월",
      "07월",
      "08월",
      "09월",
      "10월",
      "11월",
      "12월",
    ],
    monthsShort: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    today: "Today",
    clear: "Clear",
    dateFormat: "yyyy-mm-dd",
    timeFormat: "hh:ii:ss",
    firstDay: 0,
  };
  $.fn.datepicker.language["cn"] = {
    days: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
    daysShort: ["日", "一", "二", "三", "四", "五", "六"],
    daysMin: ["日", "一", "二", "三", "四", "五", "六"],
    months: [
      "01월",
      "02월",
      "03월",
      "04월",
      "05월",
      "06월",
      "07월",
      "08월",
      "09월",
      "10월",
      "11월",
      "12월",
    ],
    monthsShort: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    today: "Today",
    clear: "Clear",
    dateFormat: "yyyy-mm-dd",
    timeFormat: "hh:ii:ss",
    firstDay: 0,
  };
  $.fn.datepicker.language["tw"] = {
    days: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
    daysShort: ["日", "一", "二", "三", "四", "五", "六"],
    daysMin: ["日", "一", "二", "三", "四", "五", "六"],
    months: [
      "01월",
      "02월",
      "03월",
      "04월",
      "05월",
      "06월",
      "07월",
      "08월",
      "09월",
      "10월",
      "11월",
      "12월",
    ],
    monthsShort: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    today: "Today",
    clear: "Clear",
    dateFormat: "yyyy-mm-dd",
    timeFormat: "hh:ii:ss",
    firstDay: 0,
  };
})(jQuery);
